### ISSUE TITLE
Feature Request: Shorter time buffers

### ISSUE THREAD

**Issue by BenJamesAndo** [royshil/obs-localvocal#14]
As discussed [here](https://obsproject.com/forum/threads/localvocal-live-stream-ai-assistant.168903/#post-624233), the ability for closer to real-time caption outputting would be nice.
I'm wanting to show a live video feed in a childminding room where it's quite noisy but parents would still like to be able to hear what's happening in the main auditorium. Because of this, as close to real-time accurate captions would be great.

Perhaps if it prints the words as it discovers them could work well. Then once a set number of words is displayed, it clears the text and starts a new line.

**Comment by royshil** [comment]
Yes the true realtime output is an option of whisper.cpp
I'm still exploring how it works, but I've seen it in action in the original work.

I'll be adding the slider to determine the length of audio chunk for processing (right now fixed at 3 seconds), so that'll make it closer to realtime too. The minimum is 1 second though.

**Comment by royshil** [comment]
@BenJamesAndo can you check out #18  please?
i've implemented the step-by-step method that effectively does real-time progressive processing
see if it works out the way you thought

**Comment by BenJamesAndo** [comment]
It definitely seems more real-time. Going below 1000ms doesn't seem to do much. If the minimum is 1 second why allow under 1 second on the slider?
It only seems to display as one line of text at a time. Can it still print out two lines at a time?
I'll do some more thorough testing tomorrow.

**Comment by royshil** [comment]
i'm closing this as the change has merged

for more than one line you can use the constrained width of the Text Source
it has all kinds of means to create the subtitles in multiple lines via wrapping etc.
