### ISSUE TITLE
Automatically add CUDA DLLs to release folder

### ISSUE THREAD

**Issue by Destroy666x** [royshil/obs-localvocal#19]
Once https://github.com/royshil/obs-localvocal/pull/15 gets merged, would be nice to automatically add the 3 CUDA DLLs from `${CUDA_TOOLKIT_ROOT_DIR}\bin` to `release\obs-plugins\64bit` as described there so that people don't have to copy manually when building for that.

I tried playing with this but my 0% CMake knowledge is insufficient - couldn't get something like accepted answer here https://stackoverflow.com/questions/10671916/how-to-copy-dll-files-into-the-same-folder-as-the-executable-using-cmake to work, if that's even the most optimal way to do it. So would be nice if someone with way bigger knowledge did it properly.

Then also this part of README could get removed: https://github.com/royshil/obs-localvocal/pull/15/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L104

**Comment by royshil** [comment]
Sure I can get that done quickly

**Comment by royshil** [comment]
@Destroy666x can you check the #22 PR artifcats to see it does what you expect? 🙏

**Comment by Destroy666x** [comment]
Thanks, I built on that branch and it worked fine

**Comment by royshil** [comment]
Great thanks!
