### ISSUE TITLE
Can't use/download any other model

### ISSUE THREAD

**Issue by Destroy666x** [royshil/obs-localvocal#5]
This error is always displayed:
![image](https://github.com/royshil/obs-localvocal/assets/3606072/fa706ba7-bb16-40a2-b8e2-cdcb8eeeaebb)

**Comment by BenJamesAndo** [comment]
In the mean time I've found you can download them manually and load them into the plugins model folder. For me located at `C:\Program Files\obs-studio\data\obs-plugins\obs-localvocal\models`
Download available at https://ggml.ggerganov.com/

**Comment by royshil** [comment]
@Destroy666x can you give some extra deets like OS and versions etc.? i'll take a look asap

**Comment by Destroy666x** [comment]
Sure, versions of what?

System is Windows 10, latest patch. OBS is 29.1.3.

**Comment by stiblook** [comment]
I had the same issue on Linux, the issue was that obs didn't have permissions to download into `/usr/share/obs-plugins/obs-localvocal/`

**Comment by royshil** [comment]
I'm unable to replicate this on my Mac or Windows PC
Is this a standard OBS install? or a portable one?
What do the logs say? I am printing more detailed errors there

**Comment by Destroy666x** [comment]
Standard OBS install in Program Files. With Chocolatey if that matters, but I doubt

**Comment by BenJamesAndo** [comment]
This is what I get in my logs
`09:17:18.695: User added filter 'LocalVocal Transcription' (transcription_filter_audio_filter) to source 'Mic/Aux'
09:17:18.696: [obs-localvocal] starting whisper thread
09:17:20.710: [obs-localvocal] transcription_filter_update
09:17:20.710: [obs-localvocal] transcription_filter: update text source
09:17:20.710: [obs-localvocal] transcription_filter: update whisper model
09:17:20.710: [obs-localvocal] model path changed, reloading model
09:17:20.738: [obs-localvocal] Whisper context is null, exiting thread
09:17:20.738: [obs-localvocal] exiting whisper thread
09:17:20.738: [obs-localvocal] Checking if model models/ggml-base.bin exists...
09:17:20.739: [obs-localvocal] Model file path: (null)
09:17:20.739: [obs-localvocal] Model models/ggml-base.bin does not exist.
09:17:20.739: [obs-localvocal] Whisper model does not exist
09:17:20.741: [obs-localvocal] Model save path: ../../data/obs-plugins/obs-localvocal/models/ggml-base.bin
09:17:20.741: [obs-localvocal] Model URL: https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin
09:17:20.742: [obs-localvocal] Failed to open file ../../data/obs-plugins/obs-localvocal/models/ggml-base.bin.
09:17:20.769: [obs-localvocal] transcription_filter: update whisper params
09:17:20.788: [obs-localvocal] Model download failed`

**Comment by BenJamesAndo** [comment]
I'd say it's likely because it's trying to download the models into the OBS folder that's located in Program Files which needs admin privileges to do so, as @stiblook mentioned.
I'm trying to test it with OBS running in administrator mode but it's not opening OBS for some reason.
I believe OBS can also be installed completely in the users Appdata folder, so perhaps that's why it works for some, but not others.

**Comment by royshil** [comment]
@BenJamesAndo @Destroy666x can y'all try the builds from #17 ? 🙏 
i think i got it to work properly

**Comment by Destroy666x** [comment]
Seemed to work for me

**Comment by royshil** [comment]
@BenJamesAndo if you can take a look at this and approve it works - i will merge and we move on

**Comment by BenJamesAndo** [comment]
Works great now, thanks.

**Comment by royshil** [comment]
closing
