### ISSUE TITLE
Optionally save to a text file instead of text source

### ISSUE THREAD

**Issue by Destroy666x** [royshil/obs-localvocal#6]
Would be great if last detected sentences were optionally sent to a chosen text file instead of a chosen text source.

Why? For much easier usage outside of OBS, e.g. with external integrations. Or even inside OBS for wider support, e.g. by plugins that can read from text files in their custom sources.

**Comment by royshil** [comment]
wonderful idea - and not too difficult to implement

**Comment by klasadoroty** [comment]
Hi,
This seems to be the most important addition, too. 
Great work.

**Comment by royshil** [comment]
@Destroy666x do you have a particular format in mind? like `.srt` or the like - or just output the current caption into a `.txt` file with only the current caption (i.e. it gets deleted and overwritten)

**Comment by Destroy666x** [comment]
Basic `.txt` would be the most widely-supported format. `.srt` is a good option as well, but more niche I'd say. Supporting both would be the best ofc, but if I was to choose one, then I'd go for `.txt` first for sure.

**Comment by royshil** [comment]
implemented in #11

**Comment by royshil** [comment]
@Destroy666x @klasadoroty can yall try this build plz https://github.com/royshil/obs-localvocal/actions/runs/6124248762#artifacts ?
see if the file output works out for you
it does for me on Windows

**Comment by Destroy666x** [comment]
@royshil something feels off for now (Windows 10, OBS 29.1.3):
- OBS lagged and crashed when I copied the filter from once source to another
- the file reloads with new content but after initially saving some phrases, now it saves nothing

**Comment by royshil** [comment]
@Destroy666x 
do you have any logs or crash logs from those sessions?
i personally haven't tries filter copying, so i can try that and see if i replicate the crash

the "stops after a while" situation i can't replicate on my machine, it's pretty stable for me
so i'm suspecting another confounding factor
are you able to try this out in a fresh scene? or potentially fresh portable OBS?

**Comment by Destroy666x** [comment]
Crash:
[Crash 2023-09-08 20-04-47.txt](https://github.com/royshil/obs-localvocal/files/12563976/Crash.2023-09-08.20-04-47.txt)

2nd part may be related to performance and just huge delays as I noticed that some phrases were appearing late. I'll test more after restart since my CPU lagged a bit this session. Tooltips/description of the fields would also help.

Would you say the default setting is optimal in terms of CPU usage?

**Comment by royshil** [comment]
@Destroy666x i think i fixed the problem, can you try https://github.com/royshil/obs-localvocal/actions/runs/6142453610#artifacts ? 🙏

**Comment by royshil** [comment]
@Destroy666x did yo get a chance to check the fix for the file output?

**Comment by Destroy666x** [comment]
Oh, there was a separate fix, I thought it'd be the link to the optimization. I'll check real quick now.

**Comment by Destroy666x** [comment]
Copying the filter works consistently now, I think.

**Comment by royshil** [comment]
implemented in #11 . closing
