### ISSUE TITLE
Feature Request: Embed close captioning data into RTMP stream.

### ISSUE THREAD

**Issue by furSUDO** [royshil/obs-localvocal#7]
Embed the captions into the stream, so that the end user can enable/disable the captions client side.
Similar to [RatWithACompiler's OBS-captions-plugin](https://github.com/ratwithacompiler/OBS-captions-plugin/).

**Comment by royshil** [comment]
This is a great suggestion @furSUDO 
I will add it to the roadmap

**Comment by royshil** [comment]
this can potentially be implemented with https://docs.obsproject.com/reference-outputs#c.obs_output_output_caption_text2
i need to experiment with it, but that's how the above mentioned plugin does it

**Comment by royshil** [comment]
implemented in #13 

@furSUDO @klasadoroty are you all able to test this?

my tests with MonaServer for RTMP were successful. i did attempt to use YouTube live but I'm not sure how it works with rtmp captions steam

**Comment by royshil** [comment]
@furSUDO  nice!!
very cool. i'm merging this in and closing the issue
